image: "quay.io/podman/testing"

before_script:
  - podman --version

stages:
  - Compiles
  - Publish latest to quay

compile-amd64:
  stage: Compiles
  script:
    - podman build --runtime crun --storage-driver vfs -t stockfish:amd64 .
    - if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ] && [ "$QUAY_USERNAME" != "" ] && [ "$QUAY_PASSWORD" != "" ]; then
        podman --storage-driver vfs login quay.io --username $QUAY_USERNAME --password $QUAY_PASSWORD &&
        podman --storage-driver vfs push stockfish:amd64 quay.io/$QUAY_USERNAME/stockfish:amd64;
      fi

compile-arm64:
  stage: Compiles
  script:
    - podman build --runtime crun --storage-driver vfs --arch arm64
        --build-arg RUST_TARGET="aarch64-unknown-linux-musl"
        --build-arg MUSL_TARGET="aarch64-linux-musl"
        --build-arg STOCKFISH_TARGET="armv8"
        --build-arg FINAL_TARGET="aarch64"
        -t stockfish:arm64 .
    - if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ] && [ "$QUAY_USERNAME" != "" ] && [ "$QUAY_PASSWORD" != "" ]; then
        podman --storage-driver vfs login quay.io --username $QUAY_USERNAME --password $QUAY_PASSWORD &&
        podman --storage-driver vfs push stockfish:arm64 quay.io/$QUAY_USERNAME/stockfish:arm64;
      fi

publish-latest:
  stage: Publish latest to quay
  only:
    - current@Adrian/stockfish
  script:
    - podman --storage-driver vfs login quay.io --username $QUAY_USERNAME --password $QUAY_PASSWORD
    - podman --storage-driver vfs manifest create stockfish:latest
    - podman --storage-driver vfs pull quay.io/$QUAY_USERNAME/stockfish:arm64
    - podman --storage-driver vfs pull quay.io/$QUAY_USERNAME/stockfish:amd64
    - podman --storage-driver vfs manifest add stockfish:latest stockfish:amd64
    - podman --storage-driver vfs manifest add stockfish:latest stockfish:arm64
    - podman --storage-driver vfs manifest push stockfish:latest docker://quay.io/$QUAY_USERNAME/stockfish:latest
