#!/bin/bash
echo "Starting Stockfish on port 4000..."
while :
do
  killall -9 stockfish || true
  sleep 3
  coproc ./stockfish
  nc -l -p 4000 <&"${COPROC[0]}" >&"${COPROC[1]}"
  echo "Restarting..."
done
